version: '3.8'

services:
  gradio:
    image: "ghcr.io/darwinkel/shepardtts:main"
    ports:
      - "1337:1337"
    volumes:
      - ./current_model/:/xtts_model/:ro
      - ./mean_character_embeddings/:/mean_character_embeddings/:ro
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    environment:
      GRADIO_ANALYTICS_ENABLED: False
      GRADIO_SERVER_NAME: "0.0.0.0"
      GRADIO_SERVER_PORT: 1337
      SECRET_KEY: "changeme"
