version: '3.8'

services:
  gradio:
    build: .
    ports:
      - "1337:1337"
    volumes:
      - .:/usr/src/app
    environment:
      GRADIO_EXAMPLES_CACHE: "/tmp/"
      GRADIO_ANALYTICS_ENABLED: False
      GRADIO_SERVER_NAME: "0.0.0.0"
      GRADIO_SERVER_PORT: 1337