name: Check the code quality using linters and formatters

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"

jobs:
  ruff-format:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install poetry export plugin
        run: python -m pip install --upgrade pip poetry-plugin-export

      - name: Export dev requirements
        run: poetry export -o requirements.txt --only dev

      - name: Install dev dependencies
        run: pip install -r requirements.txt

      - name: Run format
        run: ruff format --check shepardtts

  ruff-check:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install poetry export plugin
        run: python -m pip install --upgrade pip poetry-plugin-export

      - name: Export dev requirements
        run: poetry export -o requirements.txt --only dev

      - name: Install dev dependencies
        run: pip install -r requirements.txt

      - name: Run run linter
        run: ruff check --output-format=github shepardtts

  mypy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install poetry export plugin
        run: python -m pip install --upgrade pip poetry-plugin-export

      - name: Export dev requirements
        run: poetry export -o requirements.txt --only dev

      - name: Install dev dependencies
        run: pip install -r requirements.txt

      - name: Run static type checking
        run: mypy shepardtts/*.py
