name: Check the code quality using linters and formatters

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"

jobs:
  ruff-format:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run format
        run: ruff format --check .

  ruff-check:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run run linter
        run: ruff check --output-format=github .

  mypy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install mypy
        run: |
          python -m pip install --upgrade pip
          pip install mypy

      - name: Run static type checking
        run: mypy *.py
