name: Check the code quality using linters and formatters

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"

jobs:
  ruff-format:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'poetry'

      - name: Install dev dependencies
        run: poetry install --only dev

      - name: Run format
        run: poetry run ruff format --check shepardtts

  ruff-check:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'poetry'

      - name: Install dev dependencies
        run: poetry install --only dev

      - name: Run run linter
        run: poetry run ruff check --output-format=github shepardtts

  mypy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'poetry'

      - name: Install dev dependencies
        run: poetry install --only dev

      - name: Run static type checking
        run: poetry run mypy shepardtts/*.py
