name: Run pytest in the poetry environment

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"

jobs:
  pytest-cov:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install dev dependencies
        run: poetry install

      - name: Run pytest
        run: poetry run pytest --doctest-modules --junitxml=junit/test-results-${{ matrix.python-version }}.xml --cov=shepardtts --cov-report=xml --cov-report=html tests

      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}